#!/usr/bin/env python3
"""Map radix-2 and SRT4 divider variants, alone and in cacheless cpu_top."""

from __future__ import annotations

import argparse
import datetime
import os
import pathlib
import re
import subprocess
import sys


REPO = pathlib.Path(__file__).resolve().parent.parent
FLOW = REPO / "scripts" / "synth_asap7.tcl"
DEFAULT_REPORT = REPO / "build" / "reports" / "divider_ab_areas.md"
RESULT_RE = re.compile(r"AREA_RESULT top=(\S+) label=(\S+) area=([0-9.]+) cells=(\d+)")
TOPS = (("divider", "rv32_div"), ("cacheless core", "cpu_top"))
VARIANTS = (("radix-2", "USE_SRT4=0"), ("SRT radix-4", "USE_SRT4=1"))


def update_flattened_rtl() -> None:
    proc = subprocess.run(["make", "build/cpu_full.v"], cwd=REPO, capture_output=True, text=True)
    if proc.returncode:
        raise RuntimeError(proc.stdout + proc.stderr)


def map_variant(yosys: str, scope: str, top: str, variant: str, params: str) -> tuple[float, int]:
    label = f"divider_ab_{scope}_{variant}"
    env = os.environ.copy()
    env.update({"AREA_TOP": top, "AREA_LABEL": label, "AREA_PARAMS": params})
    proc = subprocess.run([yosys, "-c", str(FLOW.relative_to(REPO))], cwd=REPO,
                          env=env, capture_output=True, text=True)
    output = proc.stdout + proc.stderr
    if proc.returncode:
        raise RuntimeError(f"ASAP7 mapping failed for {label}\n{output}")
    matches = RESULT_RE.findall(output)
    if not matches:
        raise RuntimeError(f"ASAP7 mapping did not report an area for {label}\n{output}")
    result_top, result_label, area, cells = matches[-1]
    if result_top != top or result_label != label:
        raise RuntimeError(f"ASAP7 mapping identity mismatch for {label}")
    return float(area), int(cells)


def write_report(results: dict[str, dict[str, tuple[float, int]]], report: pathlib.Path) -> None:
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Divider Radix-2 vs SRT Radix-4 Areas",
        "",
        f"> Generated by `scripts/report_divider_ab_areas.py` on {stamp}. Each "
        "variant is elaborated from the same RTL with `USE_SRT4` overridden before "
        "flattening, then mapped using the ASAP7 7.5T RVT/TT standard-cell libraries.",
        "",
        "> `cacheless core` is `cpu_top`; I$/D$ and SRAM macros are excluded. "
        "Standalone divider and flattened core rows are separately synthesized and are "
        "not additive. No timing, frequency, or IPC-times-frequency claim is implied.",
        "",
        "| scope | variant | parameters | standard-cell area (um^2) | mapped cells | area change vs radix-2 |",
        "| --- | --- | --- | ---: | ---: | ---: |",
    ]
    for scope, _ in TOPS:
        radix2_area, radix2_cells = results[scope]["radix2"]
        srt4_area, srt4_cells = results[scope]["srt4"]
        lines.append(f"| {scope} | radix-2 | `USE_SRT4=0` | {radix2_area:.6f} | {radix2_cells} | baseline |")
        lines.append(f"| {scope} | SRT radix-4 | `USE_SRT4=1` | {srt4_area:.6f} | {srt4_cells} | "
                     f"{srt4_area - radix2_area:+.6f} ({(srt4_area / radix2_area - 1):+.2%}) |")
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yosys", default="yosys")
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    args = parser.parse_args()
    try:
        update_flattened_rtl()
        results: dict[str, dict[str, tuple[float, int]]] = {}
        for scope, top in TOPS:
            results[scope] = {}
            for variant, params in VARIANTS:
                key = "radix2" if variant == "radix-2" else "srt4"
                print(f"mapping {scope}, {variant}")
                results[scope][key] = map_variant(args.yosys, scope.replace(" ", "_"),
                                                   top, key, params)
        report = pathlib.Path(args.report).resolve()
        write_report(results, report)
    except (OSError, RuntimeError) as error:
        print(f"divider A/B area: {error}", file=sys.stderr)
        return 1

    for scope, _ in TOPS:
        radix2_area, _ = results[scope]["radix2"]
        srt4_area, _ = results[scope]["srt4"]
        print(f"{scope}: radix-2={radix2_area:.6f} SRT4={srt4_area:.6f} "
              f"change={srt4_area - radix2_area:+.6f}")
    print(f"report written to {report.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
