#!/usr/bin/env python3
"""Map independently synthesizable CPU blocks to ASAP7 and summarize area.

Rows are standalone top-level mappings. They are useful for tracking a block's
implementation cost, but are not additive: whole-core synthesis can optimize
across module boundaries.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import subprocess
import sys


REPO = pathlib.Path(__file__).resolve().parent.parent
FLOW = REPO / "scripts" / "synth_asap7.tcl"
REPORT = REPO / "build" / "reports" / "module_areas.md"
RESULT_RE = re.compile(
    r"AREA_RESULT top=(\S+) label=(\S+) area=([0-9.]+) cells=(\d+)")

# These are the non-cache blocks instantiated by rv32_core. The five
# reservation-station configurations match its five concrete instantiations.
MODULES = (
    ("frontend", "rv32_frontend", ""),
    ("decoder", "rv32_decoder", ""),
    ("predictor", "rv32_predictor", ""),
    ("bpu_direction", "rv32_bpu_direction", ""),
    ("bpu_btb", "rv32_bpu_btb", ""),
    ("bpu_ras", "rv32_bpu_ras", ""),
    ("bpu_checkpoint", "rv32_bpu_checkpoint", ""),
    ("rat", "rv32_rat", ""),
    ("prf", "rv32_prf", ""),
    ("rob", "rv32_rob", ""),
    ("rs_int", "rv32_rs", "DEPTH=4,AUX_W=1"),
    ("rs_mul", "rv32_rs", "DEPTH=2,AUX_W=1"),
    ("rs_div", "rv32_rs", "DEPTH=1,AUX_W=1"),
    ("rs_branch", "rv32_rs", "DEPTH=4,AUX_W=3"),
    ("rs_mem", "rv32_rs", "DEPTH=4,AUX_W=4"),
    ("lsu", "rv32_lsu", ""),
    ("alu_unit", "rv32_alu_unit", ""),
    ("agu", "rv32_agu", ""),
    ("mul", "rv32_mul", ""),
    ("div_radix2", "rv32_div", "USE_SRT4=0"),
    ("div_srt4", "rv32_div", "USE_SRT4=1"),
    ("bru_unit", "rv32_bru_unit", ""),
)


def selected_modules(labels: list[str] | None) -> tuple[tuple[str, str, str], ...]:
    if not labels:
        return MODULES
    wanted = set(labels)
    chosen = tuple(module for module in MODULES if module[0] in wanted)
    missing = wanted - {module[0] for module in chosen}
    if missing:
        raise ValueError("unknown module label(s): " + ", ".join(sorted(missing)))
    return chosen


def map_module(yosys: str, label: str, top: str, params: str) -> tuple[float, int]:
    env = os.environ.copy()
    env.update({
        "AREA_TOP": top,
        "AREA_LABEL": label,
        "AREA_PARAMS": params,
    })
    proc = subprocess.run(
        [yosys, "-c", str(FLOW.relative_to(REPO))],
        cwd=REPO,
        env=env,
        capture_output=True,
        text=True,
    )
    output = proc.stdout + proc.stderr
    if proc.returncode:
        sys.stderr.write(output)
        raise RuntimeError(f"ASAP7 mapping failed for {label}")
    matches = RESULT_RE.findall(output)
    if not matches:
        sys.stderr.write(output)
        raise RuntimeError(f"ASAP7 mapping did not report an area for {label}")
    result_top, result_label, area, cells = matches[-1]
    if result_top != top or result_label != label:
        raise RuntimeError(f"ASAP7 mapping identity mismatch for {label}")
    return float(area), int(cells)


def update_flattened_rtl() -> None:
    proc = subprocess.run(
        ["make", "build/cpu_full.v"], cwd=REPO, capture_output=True, text=True)
    if proc.returncode:
        sys.stderr.write(proc.stdout + proc.stderr)
        raise RuntimeError("could not update build/cpu_full.v")


def write_report(results: list[tuple[str, str, str, float, int]], report: pathlib.Path) -> None:
    lines = [
        "# Standalone ASAP7 Module Areas",
        "",
        "> Generated by `scripts/report_module_areas.py` through "
        "`scripts/synth_asap7.tcl`. Each row is independently elaborated and "
        "mapped with the ASAP7 7.5T RVT/TT standard-cell libraries.",
        "",
        "> These values are not additive and must not be compared directly with "
        "the flattened `cpu_top` area: whole-core synthesis can optimize across "
        "module boundaries. I$/D$ and SRAM macros are excluded.",
        "",
        "| block | elaborated top | parameters | standard-cell area (um^2) | mapped cells | detail |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]
    for label, top, params, area, cells in results:
        parameter_text = f"`{params}`" if params else "-"
        lines.append(
            f"| {label} | `{top}` | {parameter_text} | {area:.6f} | {cells} | "
            f"`build/reports/area_{label}.md` |")
    lines.extend([
        "",
        "## Scope",
        "",
        "- `rs_*` uses the five `rv32_rs` parameter combinations instantiated by `rv32_core`.",
        "- `alu_unit` and `bru_unit` include their internal combinational ALU/BRU helpers.",
        "- `bpu_*` are the four sub-blocks instantiated by `rv32_predictor`; `predictor` remains the whole-BPU total.",
        "- `cpu_top` remains the authoritative flattened standard-cell total; run `make area` for it.",
    ])
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yosys", default="yosys", help="Yosys executable")
    parser.add_argument(
        "--module",
        action="append",
        default=None,
        help="restrict to a report label (repeatable)",
    )
    parser.add_argument("--report", default=str(REPORT), help="Markdown report path")
    args = parser.parse_args()

    try:
        modules = selected_modules(args.module)
        update_flattened_rtl()
        results = []
        for label, top, params in modules:
            suffix = f", {params}" if params else ""
            print(f"mapping {label} ({top}{suffix})")
            area, cells = map_module(args.yosys, label, top, params)
            results.append((label, top, params, area, cells))
    except (OSError, RuntimeError, ValueError) as error:
        print(f"module area: {error}", file=sys.stderr)
        return 1

    report = pathlib.Path(args.report).resolve()
    write_report(results, report)
    print()
    print(f"{'block':<12} {'area (um^2)':>14} {'cells':>10}")
    print("-" * 40)
    for label, _, _, area, cells in results:
        print(f"{label:<12} {area:>14.6f} {cells:>10}")
    try:
        report_display = report.relative_to(REPO)
    except ValueError:
        report_display = report
    print(f"\nreport written to {report_display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
