#!/usr/bin/env python3
"""Run a named correctness suite on the full cached core.

Correctness suites share the architectural and memory-shadow checks in
tb_core_ipc, but their cycle counts are intentionally not performance goldens.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import pathlib
import re
import subprocess
import sys


REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_BINARY = REPO / "build" / "obj_tb_core_ipc" / "tb_core_ipc"
KV_RE = re.compile(r"(\w+)=(\S+)")


def parse_int(value: str | int) -> int:
    return int(value, 0) if isinstance(value, str) else value


def checksum(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run_case(binary: pathlib.Path, suite: str, entry: dict, timeout: int,
             default_mask: int) -> dict:
    image = REPO / entry["image"]
    expected = parse_int(entry["expected_x10"])
    mask = parse_int(entry.get("x10_compare_mask", default_mask))
    expected_hash = entry.get("sha256", entry.get("image_sha256"))
    if not image.is_file():
        return {"name": entry["name"], "ok": False, "reason": f"missing image {image}"}
    if expected_hash and checksum(image) != expected_hash:
        return {"name": entry["name"], "ok": False, "reason": "image SHA-256 mismatch"}
    source = entry.get("source")
    source_hash = entry.get("source_sha256")
    if source and source_hash and not source.startswith(("http://", "https://")):
        source_path = REPO / source
        if not source_path.is_file() or checksum(source_path) != source_hash:
            return {"name": entry["name"], "ok": False, "reason": "source SHA-256 mismatch"}

    argv = [str(binary), f"+DATA={image.relative_to(REPO)}", f"+BENCH={suite}/{entry['name']}",
            f"+EXPECT={expected:08x}", f"+EXPECT_MASK={mask:08x}", f"+TIMEOUT={timeout}"]
    if not entry.get("check_dmem_latency", True):
        argv.append("+CHECK_DMEM_LATENCY=0")
    proc = subprocess.run(
        argv,
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    output = proc.stdout + proc.stderr
    result = {"name": entry["name"], "ok": False, "reason": "no IPC_RESULT"}
    for line in output.splitlines():
        if line.startswith("IPC_RESULT "):
            result.update(KV_RE.findall(line))
            result["ok"] = proc.returncode == 0
            result["reason"] = "" if result["ok"] else f"exited with status {proc.returncode}"
        elif line.startswith("IPC_FAIL "):
            fields = dict(KV_RE.findall(line))
            result["reason"] = fields.get("reason", "IPC_FAIL")
    if proc.returncode and result["reason"] == "no IPC_RESULT":
        result["reason"] = f"exited with status {proc.returncode}"
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--suite", choices=("basic", "advanced"), required=True)
    parser.add_argument("--binary", default=str(DEFAULT_BINARY))
    parser.add_argument("--timeout", type=int, default=20_000_000)
    parser.add_argument("--quick", action="store_true", help="skip the advanced pi case")
    parser.add_argument("--report", default=None)
    args = parser.parse_args()

    binary = pathlib.Path(args.binary)
    if not binary.is_file():
        print(f"correctness binary not found: {binary}", file=sys.stderr)
        return 1
    manifest_path = REPO / "tests" / args.suite / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    default_mask = parse_int(manifest.get("x10_compare_mask", "0xffffffff"))
    entries = manifest["tests"]
    if args.quick and args.suite == "advanced":
        entries = [entry for entry in entries if entry["name"] != "pi"]

    results = [run_case(binary, args.suite, entry, entry.get("timeout", args.timeout), default_mask)
               for entry in entries]
    print(f"\n{args.suite} correctness")
    print(f"{'test':<18} {'result':<8} {'cycles':>10} {'x10':>10}")
    print("-" * 52)
    for result in results:
        if result["ok"]:
            print(f"{result['name']:<18} PASS     {int(result['cycles']):>10} {result['x10']}")
        else:
            print(f"{result['name']:<18} FAIL     {'-':>10} {result['reason']}")

    passed = [result for result in results if result["ok"]]
    report = (pathlib.Path(args.report) if args.report else
              REPO / "build" / "reports" / f"{args.suite}.md").resolve()
    report.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [f"# {args.suite.title()} Correctness", "",
             f"> Generated by `scripts/run_correctness.py` on {stamp}. Cycle counts are diagnostic only, not timing goldens.", "",
             "| test | status | cycles | x10 |", "| --- | --- | ---: | ---: |"]
    for result in results:
        if result["ok"]:
            lines.append(f"| {result['name']} | PASS | {result['cycles']} | `{result['x10']}` |")
        else:
            lines.append(f"| {result['name']} | FAIL | - | {result['reason']} |")
    lines.extend(["", f"> Result: **{len(passed)}/{len(results)} passed**."])
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n{len(passed)}/{len(results)} passed; report written to {report.relative_to(REPO)}")
    return 0 if len(passed) == len(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
