#!/usr/bin/env python3
"""Compare radix-2 and SRT radix-4 dividers on the advanced pi image."""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import pathlib
import re
import subprocess
import sys


REPO = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = REPO / "tests" / "advanced" / "manifest.json"
DEFAULT_RADIX2 = REPO / "build" / "obj_tb_core_ipc_radix2" / "tb_core_ipc"
DEFAULT_SRT4 = REPO / "build" / "obj_tb_core_ipc_srt4" / "tb_core_ipc"
DEFAULT_REPORT = REPO / "build" / "reports" / "divider_ab_pi.md"
KV_RE = re.compile(r"(\w+)=(\S+)")
PROFILE_KEYS = (
    "alu", "load", "store", "branch", "jal", "jalr", "mul", "divrem", "other",
    "issue", "noissue_flush", "noissue_rob", "noissue_prf", "noissue_int_rs",
    "noissue_mul_rs", "noissue_div_rs", "noissue_branch_rs", "noissue_mem_rs",
    "noissue_lq", "noissue_sq", "noissue_frontend", "div_accept", "div_busy",
    "div_head_wait", "load_store_block", "cond_events", "jal_events", "jalr_events",
    "cond_mispredicts", "jal_mispredicts", "jalr_mispredicts", "cond_recoveries",
    "jump_recoveries", "control_overlap",
)


def parse_fields(line: str) -> dict[str, str]:
    return dict(KV_RE.findall(line))


def pi_entry() -> tuple[dict, int]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    entry = next(test for test in manifest["tests"] if test["name"] == "pi")
    image = REPO / entry["image"]
    if not image.is_file():
        raise RuntimeError(f"missing pi image: {image}")
    actual_hash = hashlib.sha256(image.read_bytes()).hexdigest()
    if actual_hash != entry["sha256"]:
        raise RuntimeError("pi image SHA-256 mismatch")
    return entry, int(manifest["x10_compare_mask"], 0)


def run_variant(name: str, binary: pathlib.Path, entry: dict, mask: int) -> dict:
    if not binary.is_file():
        raise RuntimeError(f"{name} binary not found: {binary}")
    expected = int(entry["expected_x10"], 0)
    timeout = int(entry["timeout"])
    proc = subprocess.run(
        [
            str(binary),
            f"+DATA={entry['image']}",
            f"+BENCH=divider_ab/{name}",
            f"+EXPECT={expected:08x}",
            f"+EXPECT_MASK={mask:08x}",
            f"+TIMEOUT={timeout}",
        ],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    output = proc.stdout + proc.stderr
    result_fields: dict[str, str] | None = None
    profile_fields: dict[str, str] | None = None
    failure = ""
    for line in output.splitlines():
        if line.startswith("IPC_RESULT "):
            result_fields = parse_fields(line)
        elif line.startswith("IPC_PROFILE "):
            profile_fields = parse_fields(line)
        elif line.startswith("IPC_FAIL "):
            failure = line
    if proc.returncode or result_fields is None or profile_fields is None:
        detail = failure or output.strip() or "no IPC_RESULT/IPC_PROFILE"
        raise RuntimeError(f"{name} pi run failed: {detail}")
    missing = [key for key in PROFILE_KEYS if key not in profile_fields]
    if missing:
        raise RuntimeError(f"{name} pi profile missing: {', '.join(missing)}")

    measured = int(result_fields["x10"], 16)
    if (measured & mask) != (expected & mask):
        raise RuntimeError(f"{name} pi x10 mismatch: {measured:08x} != {expected:08x}")
    return {
        "name": name,
        "cycles": int(result_fields["cycles"]),
        "retired": int(result_fields["retired"]),
        "ipc": int(result_fields["retired"]) / int(result_fields["cycles"]),
        "x10": measured,
        "profile": {key: int(profile_fields[key]) for key in PROFILE_KEYS},
    }


def change(radix2: int, srt4: int) -> str:
    delta = srt4 - radix2
    return f"{delta:+d} ({delta / radix2:+.2%})" if radix2 else "-"


def write_report(radix2: dict, srt4: dict, entry: dict, report: pathlib.Path) -> None:
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    profile = (("DIV accepts", "div_accept"), ("DIV busy", "div_busy"),
               ("DIV RS no-issue", "noissue_div_rs"),
               ("DIV at ROB head waiting", "div_head_wait"))
    lines = [
        "# Divider Radix-2 vs SRT Radix-4: pi",
        "",
        f"> Generated by `scripts/run_divider_ab.py` on {stamp}. Both variants use "
        "`tb_core_ipc`, its default 8 KiB I$ / 64 KiB D$, the same fixed 20-cycle "
        "memory model, and `tests/advanced/pi.data`.",
        "",
        f"> Image SHA-256 is verified against `tests/advanced/manifest.json`; full "
        f"x10 is checked against `{int(entry['expected_x10'], 0):08x}`. These are "
        "independent radix-2 and SRT4 binaries, not a comparison with the six-program IPC corpus.",
        "",
        "| variant | cycles | retired | IPC | x10 | cycle change vs radix-2 |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
        f"| radix-2 | {radix2['cycles']} | {radix2['retired']} | {radix2['ipc']:.6f} | {radix2['x10']:08x} | baseline |",
        f"| SRT radix-4 | {srt4['cycles']} | {srt4['retired']} | {srt4['ipc']:.6f} | {srt4['x10']:08x} | {change(radix2['cycles'], srt4['cycles'])} |",
        "",
        "| focused metric | radix-2 | SRT radix-4 | change |",
        "| --- | ---: | ---: | ---: |",
    ]
    for title, key in profile:
        lines.append(f"| {title} | {radix2['profile'][key]} | {srt4['profile'][key]} | "
                     f"{change(radix2['profile'][key], srt4['profile'][key])} |")
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--radix2-binary", default=str(DEFAULT_RADIX2))
    parser.add_argument("--srt4-binary", default=str(DEFAULT_SRT4))
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    args = parser.parse_args()
    try:
        entry, mask = pi_entry()
        radix2 = run_variant("radix2", pathlib.Path(args.radix2_binary), entry, mask)
        srt4 = run_variant("srt4", pathlib.Path(args.srt4_binary), entry, mask)
        report = pathlib.Path(args.report).resolve()
        write_report(radix2, srt4, entry, report)
    except RuntimeError as error:
        print(f"divider A/B: {error}", file=sys.stderr)
        return 1

    print(f"radix-2: cycles={radix2['cycles']} retired={radix2['retired']} ipc={radix2['ipc']:.6f}")
    print(f"SRT4:    cycles={srt4['cycles']} retired={srt4['retired']} ipc={srt4['ipc']:.6f}")
    print(f"cycle change: {change(radix2['cycles'], srt4['cycles'])}")
    print(f"report written to {report.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
